BakeryAppUI/Models/AccessToken.cs
namespace BakeryAppUI.Models
{
    public static class AccessToken
    {
        public static string Token { get; set; }
        public static DateTime Expiration { get; set; }

    }

}

BakeryAppUI/Models/Account.cs
namespace BakeryAppUI.Models
{
    public class Account
    {
        public decimal ServisGelir { get; set; }
        public decimal KasaDevir { get; set; }
        public decimal Devir { get; set; }
        public decimal KasaSayım { get; set; }
        public decimal CreditCard { get; set; }


    }
}

BakeryAppUI/Models/AllUser.cs
namespace BakeryAppUI.Models
{
    public class AllUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string UserName { get; set; }
        public string OperationClaim { get; set; }
    }
}

BakeryAppUI/Models/ApiUrl.cs
namespace BakeryAppUI.Models
{
    public static class ApiUrl
    {
        public static string url = "https://localhost:7207";

    }


}

BakeryAppUI/Models/BreadCounting.cs
namespace BakeryAppUI.Models
{
    public class BreadCounting
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public DateTime Date { get; set; }
    }
}

BakeryAppUI/Models/CashCounting.cs
namespace BakeryAppUI.Models
{
    public class CashCounting
    {
        public int Id { get; set; }
        public decimal TotalMoney { get; set; }
        public decimal RemainedMoney { get; set; }
        public decimal CreditCard { get; set; }
        public DateTime Date { get; set; }
    }
}

BakeryAppUI/Models/Date.cs
namespace BakeryAppUI.Models
{
    public class Date
    {
        public DateTime date { get; set; }
      
    }
}

BakeryAppUI/Models/Delivery.cs
namespace BakeryAppUI.Models
{
    public class Delivery
    {
        public int Id { get; set; }
        public DateTime DeliveryDate { get; set; }
        public decimal DeliveredAmount { get; set; }
        public decimal TotalAccumulatedAmount { get; set; }
    }
}

BakeryAppUI/Models/ErrorViewModel.cs
namespace WebAppNew.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BakeryAppUI/Models/Expense.cs
namespace BakeryAppUI.Models
{
    public class Expense 
    {
        public int Id { get; set; }
        public string Detail { get; set; } = null!;
        public DateTime Date { get; set; }
        public decimal Amount { get; set; }
    }
}

BakeryAppUI/Models/Login.cs
namespace BakeryAppUI.Models
{
    public class Login
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int OperationClaimId { get; set; }
        public string Token { get; set; }
    }

}

BakeryAppUI/Models/NetEldenAmount.cs
namespace BakeryAppUI.Models
{
    public class NetEldenAmount 
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public decimal Amount { get; set; }
    }
}

BakeryAppUI/Models/PaymentMarket.cs
namespace BakeryAppUI.Models
{
    public class PaymentMarket
    {
        public int id { get; set; }
        public decimal Amount { get; set; }
        public int MarketId { get; set; }
        public string MarketName { get; set; }
        public decimal TotalAmount { get; set; }
        public int StaleBread { get; set; }
    }
}

BakeryAppUI/Models/Product.cs
namespace BakeryAppUI.Models
{
    public class Product
    {


        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public int CategoryId { get; set; }
        public decimal Price { get; set; }
        public bool Status { get; set; }

    }
}

BakeryAppUI/Models/ProductCounting.cs
namespace BakeryAppUI.Models
{
    public class ProductCounting
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public string ProductName { get; set; }
    }
}

BakeryAppUI/Models/ServiceList.cs
namespace BakeryAppUI.Models
{
    public class ServiceList
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public int UserId { get; set; }
    }

    
}

BakeryAppUI/Models/StaleBread.cs
namespace BakeryAppUI.Models
{
    public class StaleBread
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public DateTime Date { get; set; }
        public int DoughFactoryProductId { get; set; }
        public string DoughFactoryProductName { get; set; }
    }

}

BakeryAppUI/Models/StaleProduct.cs
namespace BakeryAppUI.Models
{
    public class StaleProduct
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public DateTime Date { get; set; }
    }
}

BakeryAppUI/Models/Url.cs
namespace BakeryAppUI.Models
{
    public static class ApiUrl
    {
        public static string url = "https://localhost:7207";

    }


}

BakeryAppUI/Models/User.cs
namespace BakeryAppUI.Models
{
    public class User
    {
        public string email { get; set; }
        public string password { get; set; }
    }
}

BakeryAppUI/Models/UserViewModel.cs
namespace BakeryAppUI.Models
{
    public class UserViewModel
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string OperationClaim { get; set; }
    }
}

BakeryAppUI/Controllers/DeliveryController.cs
using BakeryAppUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace BakeryAppUI.Controllers
{
    public class DeliveryController : Controller
    {
        private readonly ApiService _apiService;

        public DeliveryController(ApiService apiService)
        {
            _apiService = apiService;
        }

        public async Task<IActionResult> Index()
        {

            string dateFormat = "yyyy-MM-dd";
            string currentDate = DateTime.Now.ToString(dateFormat);

            string paymentAmountDueUrl = $"{ApiUrl.url}/api/Delivery/GetPaymentAmountDue?date={currentDate}";

            decimal paymentAmountDue =
                await _apiService.GetApiResponse<decimal>
                (paymentAmountDueUrl);



            ViewBag.paymentAmountDue = paymentAmountDue;
            //ViewBag.paymentAmountDue = 1000;

            return View();

        }

        [HttpPost]
        public async Task<IActionResult> SaveDelivery(string toDeliver, string delivered)
        {
     
            string postDeliveryUrl = $"{ApiUrl.url}/api/Delivery/AddDelivery";
       

            Delivery delivery = new();
            delivery.DeliveryDate = DateTime.Now;
            delivery.DeliveredAmount = decimal.Parse(delivered);
            delivery.TotalAccumulatedAmount = decimal.Parse(toDeliver);
            
    
            _apiService.PostApiResponse<Delivery>(postDeliveryUrl, delivery);

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> DeliveryAll(DateTime startDate, DateTime endDate)
        {
            string dateFormat = "yyyy-MM-dd";
           

            string listDeliveryUrl = $"{ApiUrl.url}/api/Delivery/GetBetweenDates?startDate={startDate.ToString(dateFormat)}&endDate={endDate.ToString(dateFormat)}";

            List<Delivery> listDelivery =
               await _apiService.GetApiResponse<List<Delivery>>
               (listDeliveryUrl);

            return Json(listDelivery);
        }


    }

    public class ProductViewModel
    {
        public string ProductName { get; set; }
        public int YesterdayRemaining { get; set; }
        public int Produced { get; set; }
        public int TotalNet { get; set; }
    }

}

BakeryAppUI/Views/Delivery/Index.cshtml
<div class="container mt-5">
    <div class="row">

        <!-- Para Teslimat Kartı -->
        <div class="col-md-6 col-12 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <div class="form-group">
                        <h4 class="card-title">Para Teslimat</h4>
                        <p> Şuan itibari ile biriken para miktarı: @ViewBag.paymentAmountDue</p>
                        <!-- Button trigger for login form modal -->
                        <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#inlineForm">
                            Para Teslim Kayıt
                        </button>

                        
                        <div class="modal fade text-left" id="inlineForm" tabindex="-1" aria-labelledby="myModalLabel33" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title" id="myModalLabel33">Para Teslim</h4>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <form action="@Url.Action("SaveDelivery", "Delivery")" method="post" class="delivery-form" onsubmit="return validateAndSubmit()">
                                        <div class="modal-body">
                                            <label for="toDeliver" class="form-label">Teslim Edilmesi Gereken Para</label>
                                            <div class="mb-3">
                                                <input id="toDeliver" name="toDeliver" type="text" value="@ViewBag.paymentAmountDue" class="form-control" readonly>
                                            </div>
                                            <label for="delivered" class="form-label">Teslim Edilen Para</label>
                                            <div class="mb-3">
                                                <input id="delivered" name="delivered" type="number" min="0" max="@ViewBag.paymentAmountDue" placeholder="0" class="form-control" oninput="calculateRemainingAmount()" onkeydown="return validateMaxValue(event)">
                                                <div id="warning-message" class="text-danger"></div>
                                            </div>
                                            <label for="remaining" class="form-label">Kalan Para</label>
                                            <div class="mb-3">
                                                <input id="remaining" type="text" placeholder="0 TL" class="form-control" readonly>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary ms-1">
                                                Kayıt
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-md-6 col-12 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h4 class="card-title">Tarih Seçimi</h4>

                    <div class="row mb-3">
                        <label for="startDate" class="col-sm-4 col-form-label font-weight-bold fs-5">Başlangıç Tarihi</label>
                        <div class="col-sm-8">
                            <div class="input-group input-group-lg">
                                <input type="date" class="form-control font-weight-bold" id="startDate" max="@DateTime.Now.ToString("yyyy-MM-dd")" value="@DateTime.Now.ToString("yyyy-MM-dd")" >
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="endDate" class="col-sm-4 col-form-label font-weight-bold fs-5">Bitiş Tarihi</label>
                        <div class="col-sm-8">
                            <div class="input-group input-group-lg">
                                <input type="date" class="form-control font-weight-bold" id="endDate" max="@DateTime.Now.ToString("yyyy-MM-dd")" value="@DateTime.Now.ToString("yyyy-MM-dd")" >
                            </div>
                        </div>
                    </div>

                    <button type="button" class="btn btn-outline-success" onclick="submitForm()">
                        Para Teslim Kayıtlar
                    </button>

                    <div class="modal fade text-left" id="table" tabindex="-1" aria-labelledby="myModalLabel33" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="myModalLabel33">"Para Teslim" Kayıtlar</h4>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <!-- Tablo burada oluşturulacak -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>


<script>
    function submitForm() {
        var startDate = $("#startDate").val();
        var endDate = $("#endDate").val();

        // jQuery AJAX kullanarak .NET MVC controller'a istek gönderme
        $.ajax({
            url: '/Delivery/DeliveryAll',  // Controller ve Action isimlerini uygun şekilde değiştirin
            type: 'GET',
            data: { startDate: startDate, endDate: endDate },
            success: function (data) {
                // API'dan gelen verilerle tabloyu oluşturma
                createTable(data);

                // Modalı açma
                $('#table').modal('show');
            },
            error: function (error) {
                console.error('API isteği başarısız: ', error);
            }
        });
    }

    function createTable(data) {
        // Tabloyu oluşturma
        var tableHtml = '<table id="myTable" class="table table-striped">' +
            '<thead>' +
            '<tr>' +
            '<th class="th-sm">Tarih</th>' +
            '<th class="th-sm">Toplam Para</th>' +
            '<th class="th-sm">Ödenen</th>' +
            '<th class="th-sm">Kalan</th>' +
            '</tr>' +
            '</thead>' +
            '<tbody>';

        // API'dan gelen verileri tabloya ekleme
        for (var i = 0; i < data.length; i++) {

            var tarihSadece = new Date(data[i].deliveryDate).toLocaleDateString();
            tableHtml += '<tr>' +
                '<td>' + tarihSadece + '</td>' +
                '<td>' + data[i].totalAccumulatedAmount + '</td>' +
                '<td>' + data[i].deliveredAmount + '</td>' +
                '<td>' + (data[i].totalAccumulatedAmount - data[i].deliveredAmount) + '</td>' +
                '</tr>';
        }

        tableHtml += '</tbody></table>';

        // Tabloyu div içine ekleme
        $('#table .modal-body').html(tableHtml);
    }
</script>













<script>
    function validateMaxValue(event) {
        var input = document.getElementById('delivered');
        var currentValue = parseFloat(input.value) || 0;
        var maxValue = parseFloat('@ViewBag.paymentAmountDue');

        // Check if the entered value + the currently pressed key is greater than the maximum value
        if (currentValue * 10 + parseInt(event.key) > maxValue * 10) {
            event.preventDefault();
            document.getElementById('warning-message').innerText = 'Girilen miktar, teslim edilmesi gereken miktardan fazla olamaz.';
        } else {
            document.getElementById('warning-message').innerText = '';
        }
    }

    function calculateRemainingAmount() {
        var toDeliverAmount = parseFloat('@ViewBag.paymentAmountDue');
        var deliveredInput = document.getElementById('delivered');
        var deliveredAmount = parseFloat(deliveredInput.value) || 0;

        // If the entered value exceeds the maximum, set it to the maximum
        if (deliveredAmount > toDeliverAmount) {
            deliveredInput.value = toDeliverAmount.toFixed(2);
        }

        var remainingAmount = Math.max(0, toDeliverAmount - deliveredAmount);

        document.getElementById('remaining').value = remainingAmount.toFixed(2) + ' TL';
        checkAmountValidity();
    }

    function checkAmountValidity() {
        var toDeliverAmount = parseFloat('@ViewBag.paymentAmountDue');
        var deliveredAmount = parseFloat(document.getElementById('delivered').value) || 0;

        var warningMessage = document.getElementById('warning-message');

        if (deliveredAmount > toDeliverAmount) {
            warningMessage.innerText = 'Girilen miktar, teslim edilmesi gereken miktardan fazla olamaz.';
        } else {
            warningMessage.innerText = '';
        }
    }
</script>



<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.24/i18n/Turkish.json"
            }
        });
    });
</script>