BakeryAppUI/Models/AccessToken.cs
namespace BakeryAppUI.Models
{
    public static class AccessToken
    {
        public static string Token { get; set; }
        public static DateTime Expiration { get; set; }

    }

}

BakeryAppUI/Models/Account.cs
namespace BakeryAppUI.Models
{
    public class Account
    {
        public decimal ServisGelir { get; set; }
        public decimal KasaDevir { get; set; }
        public decimal Devir { get; set; }
        public decimal KasaSayım { get; set; }
        public decimal CreditCard { get; set; }


    }
}

BakeryAppUI/Models/AllUser.cs
namespace BakeryAppUI.Models
{
    public class AllUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string UserName { get; set; }
        public string OperationClaim { get; set; }
    }
}

BakeryAppUI/Models/ApiUrl.cs
namespace BakeryAppUI.Models
{
    public static class ApiUrl
    {
        public static string url = "https://localhost:7207";

    }


}

BakeryAppUI/Models/BreadCounting.cs
namespace BakeryAppUI.Models
{
    public class BreadCounting
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public DateTime Date { get; set; }
    }
}

BakeryAppUI/Models/CashCounting.cs
namespace BakeryAppUI.Models
{
    public class CashCounting
    {
        public int Id { get; set; }
        public decimal TotalMoney { get; set; }
        public decimal RemainedMoney { get; set; }
        public decimal CreditCard { get; set; }
        public DateTime Date { get; set; }
    }
}

BakeryAppUI/Models/Date.cs
namespace BakeryAppUI.Models
{
    public class Date
    {
        public DateTime date { get; set; }
      
    }
}

BakeryAppUI/Models/Delivery.cs
namespace BakeryAppUI.Models
{
    public class Delivery
    {
        public int Id { get; set; }
        public DateTime DeliveryDate { get; set; }
        public decimal DeliveredAmount { get; set; }
        public decimal TotalAccumulatedAmount { get; set; }
    }
}

BakeryAppUI/Models/ErrorViewModel.cs
namespace WebAppNew.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BakeryAppUI/Models/Expense.cs
namespace BakeryAppUI.Models
{
    public class Expense 
    {
        public int Id { get; set; }
        public string Detail { get; set; } = null!;
        public DateTime Date { get; set; }
        public decimal Amount { get; set; }
    }
}

BakeryAppUI/Models/Login.cs
namespace BakeryAppUI.Models
{
    public class Login
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int OperationClaimId { get; set; }
        public string Token { get; set; }
    }

}

BakeryAppUI/Models/NetEldenAmount.cs
namespace BakeryAppUI.Models
{
    public class NetEldenAmount 
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public decimal Amount { get; set; }
    }
}

BakeryAppUI/Models/PaymentMarket.cs
namespace BakeryAppUI.Models
{
    public class PaymentMarket
    {
        public int id { get; set; }
        public decimal Amount { get; set; }
        public int MarketId { get; set; }
        public string MarketName { get; set; }
        public decimal TotalAmount { get; set; }
        public int StaleBread { get; set; }
    }
}

BakeryAppUI/Models/Product.cs
namespace BakeryAppUI.Models
{
    public class Product
    {


        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public int CategoryId { get; set; }
        public decimal Price { get; set; }
        public bool Status { get; set; }

    }
}

BakeryAppUI/Models/ServiceList.cs
namespace BakeryAppUI.Models
{
    public class ServiceList
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public int UserId { get; set; }
    }

    
}

BakeryAppUI/Models/StaleBread.cs
namespace BakeryAppUI.Models
{
    public class StaleBread
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public DateTime Date { get; set; }
        public int DoughFactoryProductId { get; set; }
        public string DoughFactoryProductName { get; set; }
    }

}

BakeryAppUI/Models/StaleProduct.cs
namespace BakeryAppUI.Models
{
    public class StaleProduct
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public DateTime Date { get; set; }
    }
}

BakeryAppUI/Models/Url.cs
namespace BakeryAppUI.Models
{
    public static class ApiUrl
    {
        public static string url = "https://localhost:7207";

    }


}

BakeryAppUI/Models/User.cs
namespace BakeryAppUI.Models
{
    public class User
    {
        public string email { get; set; }
        public string password { get; set; }
    }
}

BakeryAppUI/Models/UserViewModel.cs
namespace BakeryAppUI.Models
{
    public class UserViewModel
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string OperationClaim { get; set; }
    }
}

BakeryAppUI/Controllers/MarketServiceController.cs
using BakeryAppUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace BakeryAppUI.Controllers
{
    public class MarketServiceController : Controller
    {
        private readonly ApiService _apiService;
        private static Date _date = new Date { date = DateTime.Now };
        private static int _serviceProductId = 1;
        public MarketServiceController(ApiService apiService)
        {
            _apiService = apiService;
        }

        public ActionResult GoToIndex(int serviceProductId)
        {
            _serviceProductId = serviceProductId;
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Index()
        {          
            //string marketBreadDetailsUrl = $"{ApiUrl.url}/api/MoneyReceivedFromMarket/GetMarketsEndOfDayCalculationWithDetail?date={_date.date.ToString("yyyy-MM-dd")}";
            string marketBreadDetailsUrl = $"{ApiUrl.url}/api/MoneyReceivedFromMarket/GetMarketsEndOfDayCalculationWithDetailByServiceId?date={_date.date.ToString("yyyy-MM-dd")}&serviceProductId={_serviceProductId}";

            //List<MarketBreadDetails> marketBreadDetails =
            //    await _apiService.GetApiResponse<List<MarketBreadDetails>>
            //    (marketBreadDetailsUrl);
            List<MarketProductDetails> marketProductDetails =
             await _apiService.GetApiResponse<List<MarketProductDetails>>
             (marketBreadDetailsUrl);



            decimal TotalAmount =0;
            decimal TotalReceivedMoney = 0;

            foreach (var item in marketProductDetails)
            {
                TotalAmount += item.TotalAmount;
                TotalReceivedMoney += item.Amount;
            }

            ViewBag.TotalAmount = TotalAmount;
            ViewBag.TotalReceivedMoney = TotalReceivedMoney;
            
            ViewBag.MarketProductDetails = marketProductDetails;
            ViewBag.date = _date.date;

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> PostDate(Date adate)
        {
            // 'model.SelectedDate' üzerinden tarih bilgisini alabilirsiniz.
            // Burada istediğiniz işlemleri gerçekleştirebilirsiniz.
            _date.date = adate.date;

            return RedirectToAction("Index"); // İsteğe bağlı olarak başka bir sayfaya yönlendirme yapabilirsiniz.
        }
    }
}

BakeryAppUI/Views/MarketService/Index.cshtml
    <!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- DataTables CSS ve JS -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap4.min.css">
<script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.18.0/font/bootstrap-icons.css">


<script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
@model BakeryAppUI.Models.Date

<div class="container mt-5">

    <div class="row mb-3">
        <div class="col-md-4">
            <div class="row">
                <label for="inputDate" class="col-sm-2 col-form-label font-weight-bold fs-5">Tarih</label>
                <div class="col-sm-10">
                    <div class="input-group input-group-lg">
                        <input type="date" class="form-control font-weight-bold" id="inputDate"
                               max="@DateTime.Now.ToString("yyyy-MM-dd")"
                               value="@ViewBag.date.ToString("yyyy-MM-dd")"
                               onchange="submitForm()">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@using (Html.BeginForm("PostDate", "MarketService", FormMethod.Post, new { id = "myForm" }))
{
    <input type="hidden" id="dateHidden" name="date" />
}

<script>
    function submitForm() {
        var selectedDate = document.getElementById("inputDate").value;
        document.getElementById("dateHidden").value = selectedDate;
        document.getElementById("myForm").submit();
    }
</script>


@if (ViewBag.MarketProductDetails.Count != 0)
{
    <div class="container">
        <div class="text-center">
            <h3>Market Servis</h3>
        </div>

        <div class="row">
            <div class="col-2">
                <button type="button" class="btn btn-primary" onclick="generatePDF()">PDF Oluştur</button>
            </div>
            <div class="col-3">
                <div class="btn-group">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Ürün Seç
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="/MarketService/GoToIndex?serviceProductId=1">Ekmek</a>
                        <a class="dropdown-item" href="/MarketService/GoToIndex?serviceProductId=2">Ramazan Pidesi</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="mb-4"></div> <!-- Butonlarla tablo arasında boşluk bırakmak için -->



        <table id="myTable" class="table table-striped">
            <thead>
                <tr>
                    <th class="th-sm">
                        Market Adı
                    </th>

                    @foreach (var column in ViewBag.MarketProductDetails[0].ProductGivenByEachService.Keys)
                    {
                        <th class="th-sm">
                            @column
                        </th>
                    }

                    <th class="th-sm">
                        Toplam Verilen
                    </th>
                    <th class="th-sm">
                        Bayat
                    </th>
                    <th class="th-sm">
                        Toplam Satış
                    </th>
                    @* <th class="th-sm">
                Birim Fiyatı
                </th> *@
                    <th class="th-sm">
                        Toplam Para
                    </th>
                    <th class="th-sm">
                        Alınan Para
                    </th>
                    <th class="th-sm">
                        Kalan Para
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var liste in ViewBag.MarketProductDetails)
                {
                    <tr>
                        <td>@liste.MarketName</td>
                        @foreach (var value in liste.ProductGivenByEachService.Values)
                        {
                            <td>
                                @(value == 0 ? "-" : value.ToString())
                            </td>
                        }
                        <td>@liste.GivenProduct</td>
                        <td>@liste.StaleProduct</td>
                        <td>@(@liste.GivenProduct - @liste.StaleProduct)</td>

                        <td>@liste.TotalAmount</td>
                        <td>@liste.Amount</td>
                        <td>@(@liste.TotalAmount - @liste.Amount)</td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="container mt-5">

            <div class="row">
                <div class="col-md-3 ms-auto">
                    <div class="alert alert-primary" role="alert">
                        <h3 class="alert-heading">Toplam Para</h3>
                        <p class="mb-0">@ViewBag.TotalAmount</p>
                    </div>
                </div>
                <div class="col-md-3 ms-auto">
                    <div class="alert alert-primary" role="alert">
                        <h3 class="alert-heading">Toplam Alınan Para</h3>
                        <p class="mb-0">@ViewBag.TotalReceivedMoney</p>
                    </div>
                </div>

                <div class="col-md-3 ms-auto">
                    <div class="alert alert-primary" role="alert">
                        <h3 class="alert-heading">Toplam Kalan Para</h3>
                        <p class="mb-0">@(@ViewBag.TotalAmount - @ViewBag.TotalReceivedMoney)</p>
                    </div>
                </div>
            </div>
        </div>



    </div>

    <!-- PDF önizleme için geniş modal -->
    <div class="modal fade" id="pdfPreviewModal" tabindex="-1" aria-labelledby="pdfPreviewModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="pdfPreviewModalLabel">PDF Önizleme</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Kapat"></button>
                </div>
                <div class="modal-body">
                    <!-- PDF önizleme için iframe -->
                    <iframe id="pdfViewer" class="embed-responsive-item" width="100%" height="500px"></iframe>
                </div>
            </div>
        </div>
    </div>




    <script>
        function generatePDF() {
            // Controller endpoint'i
            var controllerEndpoint = '@Url.Action("Index", "PdfDenem")';

            // Ajax isteği
            $.ajax({
                url: controllerEndpoint,
                type: 'GET',
                dataType: 'json', // API'den JSON formatında bir yanıt beklediğimizi belirtiyoruz
                success: function (data) {
                    // API'den gelen PDF verisini modal içindeki iframe'e ekleyerek modal'ı aç
                    var pdfViewer = document.getElementById("pdfViewer");
                    pdfViewer.src = "data:application/pdf;base64," + data;

                    var pdfPreviewModal = new bootstrap.Modal(document.getElementById("pdfPreviewModal"));
                    pdfPreviewModal.show();

                },
                error: function (error) {
                    console.error("API isteği başarısız: ", error);
                }
            });
        }
    </script>





@* 
    <!-- pdfmake -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.68/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.68/vfs_fonts.js"></script>

    <script>
        function generatePDF() {
            // Tablo verileri
            var data = [];
            var headers = [];

            // Tablo başlıkları ve verilerini doldurun
            $('#myTable thead th').each(function () {
                headers.push({ text: $(this).text().trim(), style: 'tableHeader' });
            });

            $('#myTable tbody tr').each(function () {
                var rowData = [];
                $(this).find('td').each(function () {
                    rowData.push($(this).text().trim());
                });
                data.push(rowData);
            });

            // Tarih ve firma adı
            var currentDate = new Date('@ViewBag.date.ToString("yyyy-MM-dd")');
            var formattedDate = currentDate.toLocaleDateString('tr-TR'); // Türkçe tarih formatı
            var dayOfWeek = new Intl.DateTimeFormat('tr-TR', { weekday: 'long' }).format(currentDate); // Gün

            var companyName = 'ASLANOĞLU FIRIN';

            // Toplam hesap
            var totalAmount = parseFloat('@ViewBag.TotalAmount').toFixed(2);
            var totalReceivedMoney = parseFloat('@ViewBag.TotalReceivedMoney').toFixed(2);
            var totalRemainingMoney = parseFloat('@(@ViewBag.TotalAmount - @ViewBag.TotalReceivedMoney)').toFixed(2);

            // PDF oluşturma
            var docDefinition = {
                content: [
                    {
                        columns: [
                            { width: '50%', text: companyName, style: 'companyName' },
                            { width: '50%', text: formattedDate + ' ' + dayOfWeek, style: 'date', alignment: 'right' },
                        ],
                        margin: [0, 0, 0, 10], // Boşluk
                    },
                    { text: 'Market Servisi', style: 'header' },
                    {
                        style: 'table',
                        table: {
                            headerRows: 1,
                            body: [headers, ...data]
                        }
                    },
                    { text: '\n' }, // Boş satır
                    {
                        stack: [
                            { text: 'Toplam Para: ' + totalAmount + ' TL', style: 'total', alignment: 'left' },
                            { text: 'Toplam Alınan Para: ' + totalReceivedMoney + ' TL', style: 'total', alignment: 'left' },
                            { text: 'Toplam Kalan Para: ' + totalRemainingMoney + ' TL', style: 'total', alignment: 'left' },
                        ],

                        margin: [0, 10, 0, 0], // Boşluk
                    }
                ],
                styles: {
                    companyName: {
                        fontSize: 14,
                        bold: true,
                    },
                    date: {
                        fontSize: 12,
                    },
                    header: {
                        fontSize: 18,
                        bold: true,
                        margin: [0, 0, 0, 10]
                    },
                    table: {
                        margin: [0, 5, 0, 15]
                    },
                    tableHeader: {
                        bold: true,
                        fontSize: 13,
                        color: 'black'
                    },
                    total: {
                        fontSize: 14,
                        bold: true,
                    }
                },
                pageMargins: [30, 30, 30, 30] // Sayfa kenar boşlukları
            };

            // // PDF'i indir
            // pdfMake.createPdf(docDefinition).download('tablo.pdf');

            // PDF'i oluştur
            var pdfDoc = pdfMake.createPdf(docDefinition);

            pdfDoc.getDataUrl(function (dataUrl) {
                var pdfViewer = document.getElementById('pdfViewer');
                pdfViewer.src = dataUrl;


                // Dosya ismi belirleme
                var fileName = "MarketServis_" + formattedDate + ".pdf";

                // Önceki indirme butonlarını temizle
                var existingButtons = document.querySelectorAll('.download-btn');
                existingButtons.forEach(function (button) {
                    button.remove();
                });

                // "İndir" butonu ekleyerek indirme seçeneğini sağlama
                var downloadButton = document.createElement('a');
                downloadButton.href = dataUrl;
                downloadButton.download = fileName;
                downloadButton.innerText = "Dosyayı İndir";
                downloadButton.classList.add("btn", "btn-primary", "download-btn"); // İstenirse bir CSS sınıfı ekleyebilirsiniz

                // "pdfViewer" elementine "downloadButton" elemanını ekleme
                pdfViewer.parentElement.appendChild(downloadButton);



                // Modal'ı göster
                $('#pdfPreviewModal').modal('show');
            });
        }
    </script> *@
}
else
{
    <div class="text-center mt-5">
        <i class="fas fa-exclamation-triangle fa-5x text-warning"></i>
        <h4 class="mt-3">Üzgünüz, Veri Bulunamadı</h4>
        <p>Seçtiğiniz tarihte görüntülenecek veri bulunamadı. Lütfen başka bir tarih seçin veya veri ekleyin.</p>
    </div>
}

<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.24/i18n/Turkish.json"
            }
        });
    });
</script>